// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisualStudioLauncher.WPF.Model;

#nullable disable

namespace VisualStudioLauncher.WPF.Migrations
{
    [DbContext(typeof(VSLContext))]
    [Migration("20220201205541_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("LaunchItemLaunchList", b =>
                {
                    b.Property<int>("LaunchItemsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaunchListsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LaunchItemsId", "LaunchListsId");

                    b.HasIndex("LaunchListsId");

                    b.ToTable("LaunchItemLaunchList", (string)null);
                });

            modelBuilder.Entity("VisualStudioLauncher.WPF.Model.LaunchItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgramItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProgramItemId");

                    b.ToTable("LaunchItems");
                });

            modelBuilder.Entity("VisualStudioLauncher.WPF.Model.LaunchList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LaunchLists");
                });

            modelBuilder.Entity("VisualStudioLauncher.WPF.Model.ProgramItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProgramItems");
                });

            modelBuilder.Entity("VisualStudioLauncher.WPF.Model.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("LaunchItemLaunchList", b =>
                {
                    b.HasOne("VisualStudioLauncher.WPF.Model.LaunchItem", null)
                        .WithMany()
                        .HasForeignKey("LaunchItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisualStudioLauncher.WPF.Model.LaunchList", null)
                        .WithMany()
                        .HasForeignKey("LaunchListsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VisualStudioLauncher.WPF.Model.LaunchItem", b =>
                {
                    b.HasOne("VisualStudioLauncher.WPF.Model.ProgramItem", "ProgramItem")
                        .WithMany()
                        .HasForeignKey("ProgramItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramItem");
                });
#pragma warning restore 612, 618
        }
    }
}
